name: workout_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Remove flutter_local_notifications
  url_launcher: ^6.0.0 
  percent_indicator: ^4.2.2
  provider: ^6.1.4
  hive_flutter:
  flutter_local_notifications:
  hive: ^2.2.3
  fl_chart: ^0.70.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.3
  flutter_timezone: ^4.1.0
  timezone: ^0.9.2
  # Removed date_utils due to null safety and version conflict
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  # Removed date_utils from dev_dependencies as well

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

