name: workout_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  activity_ring: ^0.3.0 # Added 2025-05-23: For Apple Watch-style progress rings
  cupertino_icons: ^1.0.8
  # Remove flutter_local_notifications
  url_launcher: ^6.0.0 
  flutter_staggered_animations:  # Use the latest version
  shimmer: 
  percent_indicator: ^4.2.2
  provider: ^6.1.4
  hive_flutter:
  flutter_local_notifications:
  hive: ^2.2.3
  audioplayers: ^5.2.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  collection: ^1.18.0 # Added 2025-05-30 for list/collection utilities
  path_provider: ^2.1.5
  image_picker: ^1.0.7
  excel: ^4.0.6
  path: ^1.8.3
  flutter_launcher_icons: ^0.14.3
  flutter_timezone: ^4.1.0
  timezone: ^0.9.2
  # Removed date_utils due to null safety and version conflict
  share_plus: ^7.2.1
  permission_handler: ^12.0.0+1
  file_picker: ^8.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  # Removed date_utils from dev_dependencies as well

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/audio/
    - assets/app_logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.jpg" # Or your custom path
  # ... other configurations